import sys
import logging

from typing import Any

from .jtag_scanner import JtagScanner, PROMPT, ROW_FORMAT, ROW_FORMAT_TDI


class JtagScannerUI:
    """Command-line user interface for driving a JtagScanner instance.

    The UI reads from sys.stdin and writes to sys.stdout by default, and it
    attaches itself to a JtagScanner instance by assigning itself to
    scanner.output so the scanner can delegate formatted output back to the
    UI when appropriate.
    """
    def __init__(self, scanner: JtagScanner):
        """Create a UI wrapper around the provided JtagScanner.

        The UI sets itself as the scanner's output so that formatted rows and
        other output generated by the scanner are routed to this UI instance.
        """
        self.scanner: JtagScanner = scanner
        self.scanner.output = self
        self.run_loop = True

    def read_cli_byte(self):
        """Read a single byte from stdin.buffer.

        Returns the integer byte value read. If stdin is not readable the
        scanner.delay method is invoked to avoid busy-waiting.
        """
        while True:
            if sys.stdin is not None and not sys.stdin.closed:
                try:
                    input_value = sys.stdin.buffer.read(1)
                    if input_value:
                        return input_value[0]
                except Exception:
                    pass
            self.scanner.delay(100)

    def read_cli_unsigned_int(self):
        """Read text bytes from stdin until newline and parse an unsigned int.

        Accepts decimal or prefixed (0x) formats via int(..., 0). Limits input to
        a modest length to avoid excessive buffering. Returns 0 when no digits
        were entered.
        """
        buffer = ""
        idx = 0

        while True:
            if sys.stdin is not None and not sys.stdin.closed:
                try:
                    input_value = sys.stdin.buffer.read(1)
                    if input_value:
                        byte = input_value[0]
                        sys.stdout.write(chr(byte if 0x20 <= byte <= 0x7e else 0x20))
                        sys.stdout.flush()
                        if idx < 20 - 1 and byte not in (0x0d, 0x0a):
                            if 0x30 <= byte <= 0x7a:
                                buffer = buffer + chr(byte)
                                idx += 1
                        else:
                            sys.stdout.write("\n")
                            sys.stdout.flush()
                            return int(buffer, 0) if buffer else 0
                except Exception:
                    pass
            self.scanner.delay(100)

    def read_cli_pin_list(self):
        """Read pin indices and ranges from stdin.

        Accepts comma/space separated integers and dash-separated ranges like
        "0-7" or mixed input such as "0-3, 6, 8-10". Returns non-negative pins
        in the entered order (ranges are expanded inclusively).
        """
        text = ""
        for _ in range(2):
            try:
                line = sys.stdin.buffer.readline()
            except Exception:
                return []

            if not line:
                return []

            text = line.decode("utf-8", errors="ignore").strip()
            if text:
                break
        if not text:
            return []

        pins: list[int] = []
        for token in text.replace(",", " ").split():
            if "-" in token:
                parts = token.split("-")
                if len(parts) != 2:
                    continue
                try:
                    start = int(parts[0])
                    end = int(parts[1])
                except (TypeError, ValueError):
                    continue
                if start < 0 or end < 0:
                    continue
                step = 1 if end >= start else -1
                pins.extend(range(start, end + step, step))
                continue

            try:
                value = int(token)
            except (TypeError, ValueError):
                continue
            if value >= 0:
                pins.append(value)
        return pins

    def print_prompt(self):
        """Write the command prompt to stdout."""
        sys.stdout.write(PROMPT)
        sys.stdout.flush()

    def id_code_banner(self):
        """Print the header line used before IDCODE output rows."""
        sys.stdout.write("| TCK | TMS | TDO |      IDCODE |")
        sys.stdout.flush()
        if self.scanner.logger.isEnabledFor(1 << 4):
            sys.stdout.write("tms|tdi|tdo|\n")
        else:
            sys.stdout.write("\n")
        sys.stdout.flush()

    def width_banner(self):
        """Print the header line used before BYPASS/width output rows."""
        sys.stdout.write("| TCK | TMS | TDO | TDI | Width |")
        sys.stdout.flush()
        if self.scanner.logger.isEnabledFor(1 << 4):
            sys.stdout.write("tms|tdi|tdo|\n")
        else:
            sys.stdout.write("\n")
        sys.stdout.flush()

    def print_result_row(self, include_tdi, value):
        """Render a formatted result row to stdout.

        This mirrors JtagScanner.print_result_row but is part of the UI so the
        formatter uses the scanner's pin attributes to produce a consistent row.
        """
        if include_tdi:
            dbgBuffer = ROW_FORMAT_TDI % (
                self.scanner.tck_pin,
                self.scanner.tms_pin,
                self.scanner.tdo_pin,
                self.scanner.tdi_pin,
                value,
            )
        else:
            dbgBuffer = ROW_FORMAT % (
                self.scanner.tck_pin,
                self.scanner.tms_pin,
                self.scanner.tdo_pin,
                value,
            )
        sys.stdout.write(dbgBuffer)
        sys.stdout.flush()

    def print_identify_start(self):
        """Print a banner indicating the start of an identification sequence."""
        sys.stdout.write("+-------------------------------+\n")
        sys.stdout.flush()

    def print_identify_success(self):
        """Print a success banner used by identification flows."""
        sys.stdout.write("+----------- SUCCESS -----------+\n")
        sys.stdout.flush()

    def print_identify_fail(self):
        """Print a failure banner used by identification flows."""
        sys.stdout.write("+------------ FAIL -------------+\n")
        sys.stdout.flush()
        
    def automatic_discovery(self):
        """Perform an automatic multi-stage discovery of JTAG pins."""
        id_hit = False
        tdi_found = False

        sys.stdout.write("     Automatically searching\n")
        sys.stdout.write("+-- Starting with IDCODE scan --+\n")
        sys.stdout.flush()
        self.id_code_banner()

        id_hit = self.scanner.identify_pins(3, self.scanner.test_id_code)

        if self.scanner.logger.isEnabledFor(20):
            self.id_code_banner()
            sys.stdout.write("+------ IDCODE complete --------+\n")
            sys.stdout.flush()

        if id_hit:
            sys.stdout.write("    TCK, TMS, and TDO found.\n")
            sys.stdout.write("\n")
            sys.stdout.write("+-- BYPASS searching, just TDI -+\n")
            sys.stdout.flush()
            self.width_banner()
            self.scanner.pin_blacklist = self.scanner.bit_write(self.scanner.pin_blacklist,
                                                                self.scanner.tck_pin, 1)
            self.scanner.pin_blacklist = self.scanner.bit_write(self.scanner.pin_blacklist,
                                                                self.scanner.tms_pin, 1)
            self.scanner.pin_blacklist = self.scanner.bit_write(self.scanner.pin_blacklist,
                                                                self.scanner.tdo_pin, 1)
            tdi_found = self.scanner.identify_pins(1, self.scanner.test_bypass)
            self.scanner.pin_blacklist = 0

        if not id_hit or not tdi_found:
            sys.stdout.write(" No valid TCK, TMS, and TDO found\n")
            sys.stdout.write("  Press 'b' for full bypass scan\n")
            sys.stdout.flush()
            
    def icode_discovery(self):
        """Perform an IDCODE search using TCK/TMS/TDO."""
        sys.stdout.write("+------ IDCODE searching -------+\n")
        sys.stdout.flush()
        self.id_code_banner()
        self.scanner.identify_pins(3, self.scanner.test_id_code)
        if self.scanner.logger.isEnabledFor(20):
            self.id_code_banner()
            sys.stdout.write("+------ IDCODE complete --------+\n")
            sys.stdout.flush()

    def bypass_discovery(self):
        """Perform a BYPASS search using TCK/TMS/TDO/TDI."""
        sys.stdout.write("+------ BYPASS searching -------+\n")
        sys.stdout.flush()
        self.width_banner()
        self.scanner.identify_pins(4, self.scanner.test_bypass)
        if self.scanner.logger.isEnabledFor(20):
            self.width_banner()
            sys.stdout.write("+------ BYPASS complete --------+\n")
            sys.stdout.flush()

    def tdi_only_discovery(self):
        """Perform a BYPASS search using only TDI, blacklisting TCK/TMS/TDO."""
        sys.stdout.write("+-- BYPASS searching, just TDI -+\n")
        sys.stdout.flush()
        self.width_banner()
        self.scanner.pin_blacklist = self.scanner.bit_write(self.scanner.pin_blacklist,
                                                            self.scanner.tck_pin, 1)
        self.scanner.pin_blacklist = self.scanner.bit_write(self.scanner.pin_blacklist,
                                                            self.scanner.tms_pin, 1)
        self.scanner.pin_blacklist = self.scanner.bit_write(self.scanner.pin_blacklist,
                                                            self.scanner.tdo_pin, 1)
        self.scanner.identify_pins(1, self.scanner.test_bypass)
        self.scanner.pin_blacklist = 0

    def setup_pin_list(self):
        """Prompt the user to enter a comma-separated list of IO pins and run a scan."""
        sys.stdout.write("Enter IO pin list (comma separated value or dash-separated range): ")
        sys.stdout.flush()
        pins = self.read_cli_pin_list()
        if pins:
            for pin in pins:
                if pin not in self.scanner.io_pin_list:
                    self.scanner.io_pin_list.append(pin)
            sys.stdout.write("IO pin list set to ")
            sys.stdout.write(str(self.scanner.io_pin_list) + "\n")
            sys.stdout.flush()

            hardware_result = self.scanner.run_jtag_scan(
                candidate_channels=self.scanner.io_pin_list,
                runtime_policy="hardware",
            )
            if hardware_result.ok:
                sys.stdout.write("hardware mapping: " + str(hardware_result.mapping) + "\n")
            else:
                sys.stdout.write("hardware scan failed: " + hardware_result.reason + "\n")
            sys.stdout.flush()
        else:
            sys.stdout.write("No IO pins were accepted from the CLI input\n")
            sys.stdout.flush()

    def pin_mask(self):
        """Prompt the user to enter a pin mask and set it on the scanner."""
        sys.stdout.write("Enter pin mask ")
        sys.stdout.flush()
        self.scanner.pin_mask = self.read_cli_unsigned_int()
        self.scanner.pin_max = self.scanner.get_max_pin_from_mask(self.scanner.pin_mask)
        sys.stdout.write("Pin mask set to ")
        sys.stdout.write(bin(self.scanner.pin_mask) + "\n")
        sys.stdout.flush()

    def cycle_log_level(self):
        """Cycle the scanner's log level through ERROR, WARNING, INFO, DEBUG."""
        current = self.scanner.logger.level
        new_level = {
            logging.ERROR: logging.WARNING,
            logging.WARNING: logging.INFO,
            logging.INFO: logging.DEBUG,
            logging.DEBUG: logging.ERROR,
        }[current]
        self.scanner.set_log_level(new_level)
        sys.stdout.write("Log level set to ")
        sys.stdout.write(self.scanner.get_log_level_name() + "\n")
        sys.stdout.flush()

    def set_log_level_by_name(self):
        """Prompt the user to enter a log level name and set it on the scanner."""
        sys.stdout.write("Enter log level (DEBUG, INFO, WARNING, ERROR): ")
        sys.stdout.flush()
        level = self.read_cli_pin_list()
        if level:
            level_name = str(level[0]).upper()
            try:
                self.scanner.set_log_level(level_name)
                sys.stdout.write("Log level set to ")
                sys.stdout.write(self.scanner.get_log_level_name() + "\n")
            except (TypeError, ValueError):
                sys.stdout.write("Invalid log level: " + str(level_name) + "\n")
        else:
            sys.stdout.write("No log level entered\n")
        sys.stdout.flush()

    def set_clock_half_cycle(self):
        """Prompt the user to enter a clock half cycle in microseconds and set it on the scanner."""
        sys.stdout.write("Enter clock half cycle in microseconds ")
        sys.stdout.flush()
        self.scanner.clock_half_cycle_us = self.read_cli_unsigned_int()
        sys.stdout.write("Clock half cycle set to ")
        sys.stdout.write(str(self.scanner.clock_half_cycle_us) + "\n")
        sys.stdout.flush()


    def display_help(self):
        """Print a simple help menu to stdout."""
        string_title = "+-------------------------------+\n"
        sys.stdout.write(string_title)
        sys.stdout.write("|  JTAGscan Jtag Pinout Finder  |\n")
        
        backend_value = getattr(getattr(self.scanner, "backend", None), "backend_name", "unknown")
        backend_name = "|  Hardware backend: " + backend_value
        padding_len = len(string_title) - len(backend_name) - 3
        if padding_len > 0:
            backend_name += " " * padding_len
        sys.stdout.write(backend_name + " |\n")
        sys.stdout.write(string_title)
        
        sys.stdout.write(" a - Automatically find all pins\n")
        sys.stdout.write(" i - IDCODE search for pins\n")
        sys.stdout.write(" b - BYPASS search for pins\n")
        sys.stdout.write(" t - TDI-only BYPASS search\n")
        sys.stdout.write(" p - setup IO pin list\n")
        sys.stdout.write(" m - set pin mask, current: " + hex(self.scanner.pin_mask) + "\n")
        sys.stdout.write(" d - cycle log level. current: " + self.scanner.get_log_level_name()
                         + "\n")
        sys.stdout.write(" c - half cycle us, current: " + str(self.scanner.clock_half_cycle_us)
                         + "\n")
        sys.stdout.write(" L - set log level by name\n")
        sys.stdout.write(" h - print this help\n")
        sys.stdout.write(" q - quit\n")
        sys.stdout.write(string_title)
        sys.stdout.flush()

    def command_line_interface(self):
        """Read one command from the CLI and execute the corresponding action."""
        selection = self.read_cli_byte()
        if isinstance(selection, int):
            selection = chr(selection)

        match selection:

            case 'a':
                self.automatic_discovery()

            case 'i':
                self.icode_discovery()

            case 'b':
                self.bypass_discovery()

            case 't':
                self.tdi_only_discovery()

            case 'p':
                self.setup_pin_list()

            case 'm':
                self.pin_mask()

            case 'd':
                self.cycle_log_level()

            case 'L':
                self.set_log_level_by_name()

            case 'c':
                self.set_clock_half_cycle()

            case 'h':
                self.display_help()

            case 'q':
                self.run_loop = False

            case _:
                sys.stdout.write("Unknown command: " + str(selection) + "\n")

    def setup(self, input_args: dict[str, Any] | None = None) -> None:
        """Prepare the scanner for interactive use.

        Sets the scanner's pin_max based on its pin_mask and configures a sane
        default log level for interactive sessions.
        """
        self.scanner.pin_max = self.scanner.get_max_pin_from_mask(self.scanner.pin_mask)
        self.scanner.set_log_level(logging.INFO)

    def loop(self):
        """Single iteration of the interactive UI loop.

        Prints a prompt and processes one entered command via
        command_line_interface.
        """
        self.print_prompt()
        self.command_line_interface()
